@baseUrl = {{$dotenv baseUrl}}

## CREATE A (test) NEW USER (this will create a link for email validation)
## If SMTP is disabled, then you won't actually get an email verification
## You can also create a proper user with 018-signup.http
POST {{baseUrl}}/session/ HTTP/1.1
content-type: application/json
WWW-Authentication: upass
Authorization: none
Cookie: username=someUser2@gmail.com
Cookie: password=somePassword

###

## INITIAL LOGIN
# @name login
GET {{baseUrl}}/session/ HTTP/1.1
content-type: application/json
WWW-Authentication: upass
Authorization: none
Cookie: username=verifiedUser@gmail.com
Cookie: password=12345678

###

## SUBSEQUENT Requests
@authToken = {{login.response.headers.Authorization}}

GET {{baseUrl}}/session/ HTTP/1.1
content-type: application/json
WWW-Authentication: token
Authorization: {{authToken}}

{}
###