@baseUrl = {{$dotenv baseUrl}}

POST {{baseUrl}}/forgotPassword/ HTTP/1.1
content-type: application/json
WWW-Authentication: none
Authorization: none
# expected response (roughly):
# { "status": "email sent to verifiedUser@gmail.com." }

{
    "email": "verifiedUser@gmail.com"
}


###

# check redis Db: 5 for a valid link (this hard coded hash wont work.)
# This endpoint is so that React can create an event driven button for the POST request
GET {{baseUrl}}/forgotPassword/HuMTDSOFvRjHZvQWVjFfbyyZWTvtxeLg HTTP/1.1
content-type: application/json
WWW-Authentication: none
Authorization: none
# ~expeceded response (roughly):
#  { "post": "hrkqMAjBUysjBiEnTgXLCWuSrdqDmplj", "status": "ready for a reset" }
#
# React should check the response.post string, and use that for the next post request to
# change the password

###

# check redis Db: 5 for a valid link (this hard coded hash wont work.)
POST {{baseUrl}}/forgotPassword/HuMTDSOFvRjHZvQWVjFfbyyZWTvtxeLg HTTP/1.1
content-type: application/json
WWW-Authentication: none
Authorization: none

{
    "password1": "plainTextPassword",
    "password2": "plainTextPassword"
}