@baseUrl = {{$dotenv baseUrl}}

## INITIAL LOGIN (need to have a token to view cart)
# @name login
GET {{baseUrl}}/session/ HTTP/1.1
content-type: application/json
WWW-Authentication: upass
Authorization: none
Cookie: username=verifiedUser@gmail.com
Cookie: password=12345678

###

## SUBSEQUENT Requests (then you can add to cart)
@authToken = {{login.response.headers.Authorization}}

GET {{baseUrl}}/cart HTTP/1.1
content-type: application/json
WWW-Authentication: token
Authorization: {{authToken}}

{}
###